export const THEME_LIST_REQUEST = 'THEME_LIST_REQUEST'
export const THEME_LIST_SUCCESS = 'THEME_LIST_SUCCESS'
export const THEME_LIST_FAIL = 'THEME_LIST_FAIL'

export const THEME_DETAILS_REQUEST = 'THEME_DETAILS_REQUEST'
export const THEME_DETAILS_SUCCESS = 'THEME_DETAILS_SUCCESS'
export const THEME_DETAILS_FAIL = 'THEME_DETAILS_FAIL'

export const THEME_ADD_REQUEST = 'THEME_ADD_REQUEST'
export const THEME_ADD_SUCCESS = 'THEME_ADD_SUCCESS'
export const THEME_ADD_FAIL = 'THEME_ADD_FAIL'

export const THEME_EDIT_REQUEST = 'THEME_EDIT_REQUEST'
export const THEME_EDIT_SUCCESS = 'THEME_EDIT_SUCCESS'
export const THEME_EDIT_FAIL = 'THEME_EDIT_FAIL'
export const THEME_EDIT_RESET = 'THEME_EDIT_RESET'

export const THEME_DELETE_REQUEST = 'THEME_DELETE_REQUEST'
export const THEME_DELETE_SUCCESS = 'THEME_DELETE_SUCCESS'
export const THEME_DELETE_FAIL = 'THEME_DELETE_FAIL'



